
package assignementskincare;

public class Skincare extends javax.swing.JFrame {

    public Skincare() {
        initComponents();
    }
    
    public class BrandsSkincare {
 
    String Safi;
    String Loreal;
    String Simple;
    String Himalaya;
    String Biore;
    private String types = "Types of skincare: Oily, Dry, Combination";
    private String howUsing = "Step using skincare : 1:Cleansing your face 2:put the toner 3:put the moisturing 4:put the serum";

   

     BrandsSkincare(String pack1, String pack2, String pack3, String pack4, String pack5) {
        this.Safi = pack1;
        this.Loreal = pack2;
        this.Simple = pack3;
        this.Himalaya = pack4;
        this.Biore = pack5;
    }
   

    public void setString(String pack1, String pack2, String pack3, String pack4, String pack5) {
        this.Safi = "Cleansing + moisturing + serum + toner";
        this.Loreal = "Mosituring + serum";
        this.Simple = "Cleansing+ toner + moisturing + serum";
        this.Himalaya = "Cleansing + moisturing";
        this.Biore = "Toner + moisturing";
    }

    public String getStringOne() {
        return Safi;
    }

    public String getStringTwo() {
        return Loreal;
    }

    public String getStringThree() {
        return Simple;
    }

    public String getStringFour() {
        return Himalaya;
    }

    public String getStringFive() {
        return Biore;
    }
    
     public String getTypes(){
    return types;
    }

    public void setRadio(String mytype){
    this.types = mytype;
    }
    
     public String getUsingSkincare(){
    return howUsing;
    }

    public void sethowUsing(String mystepSkincare){
    this.howUsing = mystepSkincare;
    }
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("SKINCARE");

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("BRANDS SKINCARE:");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("CATEGORY SKINCARE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 153, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("ADD");

        jButton4.setBackground(new java.awt.Color(255, 153, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("RESET");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton2)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(260, 260, 260)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jButton4)))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(68, 68, 68)
                .addComponent(jButton2)
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
     class BrandsSkincare {
     
        
    String Safi;
    String Loreal;
    String Simple;
    String Himalaya;
    String Biore;
    private String types = "Types of skincare: Oily, Dry, Combination";
    private String howUsing = "Step using skincare : 1:Cleansing your face 2:put the toner 3:put the moisturing 4:put the serum";

     

     BrandsSkincare(String pack1, String pack2, String pack3, String pack4, String pack5) {
        this.Safi = pack1;
        this.Loreal = pack2;
        this.Simple = pack3;
        this.Himalaya = pack4;
        this.Biore = pack5;
    }
     
   

    public void setString(String pack1, String pack2, String pack3, String pack4, String pack5) {
        this.Safi = "Cleansing + moisturing + serum + toner";
        this.Loreal = "Mosituring + serum";
        this.Simple = "Cleansing+ toner + moisturing + serum";
        this.Himalaya = "Cleansing + moisturing";
        this.Biore = "Toner + moisturing";
    }

    public String getStringOne() {
        return Safi;
    }

    public String getStringTwo() {
        return Loreal;
    }

    public String getStringThree() {
        return Simple;
    }

    public String getStringFour() {
        return Himalaya;
    }

    public String getStringFive() {
        return Biore;
    }
    
     public String getTypes(){
    return types;
    }

    public void setRadio(String mytype){
    this.types = mytype;
    }
    
     public String getUsingSkincare(){
    return howUsing;
    }

    public void sethowUsing(String mystepSkincare){
    this.howUsing = mystepSkincare;
    
    

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CategorySkincare c = new CategorySkincare("\ncleansing","\nmoisturing","\nserum","\ntoner");
        assignementskincare.BrandsSkincare b = new assignementskincare.BrandsSkincare("Safi","Loreal","Simple","Himalaya","Biore");
        System.out.println("Brands skincare type: "+c.toString());
        
        b.setString("pack 1","pack 2","pack 3","pack 4","pack 5");
        System.out.println("First brand skincare Safi: "+b.getStringOne());
        System.out.println("Second brand skincare Loreal: "+b.getStringTwo());
        System.out.println("Third brand skincare Simple: "+b.getStringThree());
        System.out.println("Fourth brand skincare Himalaya: "+b.getStringFour());
        System.out.println("Fifth brand skincare Biore: "+b.getStringFive());
        
        System.out.println(b.getTypes());
        System.out.println(b.getUsingSkincare());
        System.out.println(c.getplace());
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       System.out.println(add.BrandsSkincare); // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    public static void main(String args[]) {
    
 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Skincare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Skincare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Skincare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Skincare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                    Skincare window = new Skincare();
                   new Skincare().setVisible(true);
                } catch (exception e) {
                    e.printStackTrace();
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
}
